apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanager
  labels:
    app: certmanager
    chart: {{ template "certmanager.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificates/status", "certificates/finalizers", "certificaterequests", "certificaterequests/status", "issuers", "issuers/status", "clusterissuers", "clusterissuers/status"]
    verbs: ["*"]
  - apiGroups: ["acme.cert-manager.io"]
    resources: ["orders", "orders/status", "orders/finalizers", "challenges", "challenges/status"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "events", "services", "pods"]
    verbs: ["*"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certmanager
  labels:
    app: certmanager
    chart: {{ template "certmanager.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certmanager
subjects:
  - name: certmanager
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
